esphome:
  name: node02
  platform: ESP8266
  board: d1_mini
  arduino_version: 2.7.4

logger:
  level: INFO
  baud_rate: 0

api:
  reboot_timeout: 0s

meshmesh:
  baud_rate: 0
  tx_buffer_size: 0
  channel: 9
  password: !secret meshmesh_password

socket:
  implementation: meshmesh_esp8266

mdns:
  disabled: true

switch:
  - platform: gpio
    pin: D4
    inverted: true
    name: "Blue LEDS"

